sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t willcarver123/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true willcarver123/docker-react yarn test
